version: '3.9'
name: todo-api-dto

services:
  todo-api-dto-app:
    container_name: todo-api-dto-app-container
    image: todo-api-dto-app-image
    #platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/dockerdemo.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Pass@*****
    volumes:
      - ./https:/https:ro
    ports:
      - '5000:80'
      - '443:443'
    networks:
      - todo-api-dto

networks:
  todo-api-dto:
    driver: bridge